openapi: 3.0.3
info:
  title: WalletPlus
  description: 'A simple API for a platform that empowers customers to use their e-Wallet to do various type of transaction'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/register:
    post:
      summary: 'Registers a new user.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email of the  user.'
                  example: testuser@example.com
                password:
                  type: string
                  description: ''
                  example: autem
                first_name:
                  type: string
                  description: ''
                  example: cumque
                last_name:
                  type: string
                  description: ''
                  example: consequatur
                phone:
                  type: numeric
                  description: ''
                  example: sint
              required:
                - email
                - password
                - first_name
                - last_name
                - phone
      security: []
  /api/v1/login:
    post:
      summary: 'Logs in a user and generates and returns an API key user.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email of the  user.'
                  example: testuser@example.com
                password:
                  type: string
                  description: 'The password of the  user.'
                  example: secret
              required:
                - email
                - password
      security: []
  '/api/v1/fund/{id}':
    post:
      summary: 'Fund a user''s wallet.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                  description: 'The amount'
                  example: '50'
              required:
                - amount
    parameters:
      -
        in: path
        name: id
        description: ''
        example: placeat
        required: true
        schema:
          type: string
  '/api/v1/transfer/{id}':
    post:
      summary: 'Transfer between users.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                  description: 'The amount'
                  example: '50'
              required:
                - amount
    parameters:
      -
        in: path
        name: id
        description: ''
        example: nihil
        required: true
        schema:
          type: string
  '/api/v1/transactions/{id}':
    get:
      summary: 'Get a list of a user''s transactions.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'Incorrect credentials. Please pass a valid Authorization header'
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: ''
        example: tempora
        required: true
        schema:
          type: string
  '/api/v1/spend_currency/{id}':
    post:
      summary: 'Spend money from a user''s wallet.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: string
                  description: 'The amount.'
                  example: '50'
              required:
                - amount
    parameters:
      -
        in: path
        name: id
        description: ''
        example: quia
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
